### ISSUE TITLE
Jackson not marked as ignorable

### ISSUE THREAD

**Issue by luisalves00** [jenkinsci/maven-artifact-choicelistprovider-plugin#22]
### Jenkins and plugins versions report

The following occurs on our system when using the plugin:

{{Apr 07, 2022 1:24:05 PM WARNING org.jenkinsci.plugins.maven_artifact_choicelistprovider.nexus3.Nexus3RestApiSearchService callService
failed to map
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "uploader" (class org.jenkinsci.plugins.maven_artifact_choicelistprovider.nexus3.Item), not marked as ignorable (10 known properties: "checksum", "path", "downloadUrl", "repository", "id", "lastModified", "contentType", "format", "npm", "maven2"])
at [Source: (StringReader); line: 16, column: 22] (through reference chain: org.jenkinsci.plugins.maven_artifact_choicelistprovider.nexus3.Nexus3RestResponse["items"]>java.lang.Object[][0]>org.jenkinsci.plugins.maven_artifact_choicelistprovider.nexus3.Item["uploader"])
at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:855)

From the source I see you already have the fix:

![image](https://user-images.githubusercontent.com/3064521/162198405-2cca3b97-5d02-49f4-ae12-a51c6f7ad9f7.png)

Can you be kind and create a new patch release?

Thanks in Advance.

### What Operating System are you using (both controller, and any agents involved in the problem)?

Not relevant

### Reproduction steps

Integrate with newer versions of Sonatype Nexus Repository Manager,

### Expected Results

No exception.

### Actual Results

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "uploader" (class org.jenkinsci.plugins.maven_artifact_choicelistprovider.nexus3.Item), not marked as ignorable (10 known properties: "checksum", "path", "downloadUrl", "repository", "id", "lastModified", "contentType", "format", "npm", "maven2"])

**Comment by phreakadelle** [comment]
Thanks @luisalves00. This has already been reported by Markus in ticket #20 .

The new build is on the way.

**Comment by luisalves00** [comment]
Great. Thanks a lot.
