### ISSUE TITLE
Extended Choice Parameter - Nexus 3 add new attributes causing a mapping error

### ISSUE THREAD

**Issue by fyrnaga** [jenkinsci/maven-artifact-choicelistprovider-plugin#5]
We recently updated our nexus repository and we are having issues with the Extended Choice Parameter.
We were using it to fetch npm artifact versions and now it is not working.

I checked the logs and it is failing because of a mapping error. It seems that nexus added some information in their asset to add the npm component.

, {
    "id" : "....",
    "repository" : "npm-public",
    "format" : "npm",
    "group" : "cloudops",
    "name" : "cloudmc-ui",
    "version" : "21.1.0-SNAPSHOT",
    "assets" : [ {
      "downloadUrl" : "https://repository/npm-public/@cloudops/cloudmc-ui/-/cloudmc-ui-21.1.0-SNAPSHOT.tgz",
      "path" : "@cloudops/cloudmc-ui/-/cloudmc-ui-21.1.0-SNAPSHOT.tgz",
      "id" : "....",
      "repository" : "npm-public",
      "format" : "npm",
      "checksum" : {
        "sha1" : "...."
      },
      "contentType" : "application/x-tgz",
      "lastModified" : "2020-06-09T16:00:56.682+00:00",
      "npm" : {
        "name" : "@cloudops/cloudmc-ui",
        "version" : "21.1.0-SNAPSHOT"
      }
    } ]
...

From the logs we have the following error in jenkins.

2021-01-08 21:01:09.267+0000 [id=52087] WARNING o.j.p.m.n.Nexus3RestApiSearchService#callService: failed to map
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "npm" (class org.jenkinsci.plugins.maven_artifact_choicelistprovider.nexus3.Item), not marked as ignorable (9 known properties: "checksum", "path", "downloadUrl", "repository", "id", "lastModified", "contentType", "format", "maven2"])
 at [Source: (String)"{
  "items" : [ {
    "downloadUrl" : "https://..../repository/npm-internal/@cloudops/cloudmc-ui/-/cloudmc-ui-11.0.0.tgz",
    "path" : "@cloudops/cloudmc-ui/-/cloudmc-ui-11.0.0.tgz",
    "id" : "....",
    "repository" : "npm-internal",
    "format" : "npm",
    "checksum" : {
      "sha1" : "...."
    },
    "contentType" : "application/x-tgz",
    "lastModified" : "2018-10-18T20:18:39.900"[truncated 29334 chars]; line: 13, column: 14] (through reference chain: org.jenkinsci.plugins.maven_artifact_choicelistprovider.nexus3.Nexus3RestResponse["items"]->java.lang.Object[][0]->org.jenkinsci.plugins.maven_artifact_choicelistprovider.nexus3.Item["npm"])
at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823)
at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1153)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:195)
at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:21)
at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
at org.jenkinsci.plugins.maven_artifact_choicelistprovider.nexus3.Nexus3RestApiSearchService.callService(Nexus3RestApiSearchService.java:54)
at org.jenkinsci.plugins.maven_artifact_choicelistprovider.AbstractRESTfulVersionReader.retrieveVersions(AbstractRESTfulVersionReader.java:70)
at org.jenkinsci.plugins.maven_artifact_choicelistprovider.AbstractMavenArtifactChoiceListProvider.readURL(AbstractMavenArtifactChoiceListProvider.java:116)
at org.jenkinsci.plugins.maven_artifact_choicelistprovider.nexus3.Nexus3ChoiceListProvider$Nexus3DescriptorImpl.wrapTestConnection(Nexus3ChoiceListProvider.java:98)
at org.jenkinsci.plugins.maven_artifact_choicelistprovider.AbstractMavenArtifactDescriptorImpl.performTest(AbstractMavenArtifactDescriptorImpl.java:59)
at org.jenkinsci.plugins.maven_artifact_choicelistprovider.nexus3.Nexus3ChoiceListProvider$Nexus3DescriptorImpl.doTest(Nexus3ChoiceListProvider.java:92)
at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
 
Is it possible to come back if this is a bug on your end, new version and when it could be fixed. If this is not the right channel, which one should I used (https://github.com/jenkins-infra/plugin-site/issues/559)

Thanks,

Regards,

Alain

**Comment by phreakadelle** [comment]
Hey,

we have had a similiar issues some days ago with Nexus3 and Maven2 artifacts. The assets have changed. Markus did a fix for Maven2, maybe you can provide a PR with a similar change for NPM: 

https://github.com/jenkinsci/maven-artifact-choicelistprovider-plugin/commit/2102bb1ad8adc382c47f552d00ebd7cb40659fc2

I dont have a Nexus3 instance available for testing, so its hard for me to fix it with out the ability to test it.

Regards
Stephan

**Comment by fyrnaga** [comment]
I will take a look

**Comment by fyrnaga** [comment]
I investigated and it seems that the problem is already solved. after version 1.5.4 (1.6.x and above). I don't know why it is not offered to be updated. I will check why the update through the interface is not showing newer versions

**Comment by fyrnaga** [comment]
I manage to get the plugin installed. However, now it seems not to get the list of values from nexus. I search the logs and i think i know what is the problem.
`
2021-01-29 13:27:19.042+0000 [id=17]	INFO	o.j.p.m.n.Nexus3RestApiSearchService#callService: URI: http://..../service/rest/v1/search/assets?name=%5Bcloudmc-ui%5D&repository=%5Bnpm-internal%5D&group=%5Bcloudops%5D
2021-01-29 13:27:19.053+0000 [id=17]	INFO	o.j.p.m.AbstractMavenArtifactChoiceListProvider#readURL: failed to retrieve versions from repository for g:cloudops, a:cloudmc-ui, p:, c:
javax.ws.rs.RedirectionException: HTTP 301 Moved Permanently
	at org.glassfish.jersey.client.JerseyInvocation.createExceptionForFamily(JerseyInvocation.java:1053)
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1039)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:819)
	at org.glassfish.jersey.client.JerseyInvocation.access$700(JerseyInvocation.java:92)
	at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:697)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:420)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:316)
	at org.jenkinsci.plugins.maven_artifact_choicelistprovider.nexus3.Nexus3RestApiSearchService.callService(Nexus3RestApiSearchService.java:56)
	at org.jenkinsci.plugins.maven_artifact_choicelistprovider.AbstractRESTfulVersionReader.retrieveVersions(AbstractRESTfulVersionReader.java:71)
Caused: org.jenkinsci.plugins.maven_artifact_choicelistprovider.VersionReaderException: failed to retrieve versions from repository for r:http://..../, g:cloudops, a:cloudmc-ui, p:, c:ValidAndInvalidClassifier [valid=] [invalid=]]
`

**Comment by fyrnaga** [comment]
@phreakadelle Hi just pushed the PR to resolve the issue for nexus 3 not finding elements: https://github.com/jenkinsci/maven-artifact-choicelistprovider-plugin/pull/7
